apps_gerais/funcionarios/urls.py
from django.urls import path
from .views import (FuncionariosList,
                    FuncionarioEdit,
                    FuncionarioDelete,
                    FuncionarioNovo,
                    FuncionarioDetail,
                    Pdf
)

from .views import relatorio_funcionarios

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('novo/', FuncionarioNovo.as_view(), name='create_funcionario'),
    path('editar/<int:pk>/', FuncionarioEdit.as_view(), name='update_funcionario'),
    path('delete/<int:pk>/', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('detalhe/<int:pk>/', FuncionarioDetail.as_view(), name='detalhe_funcionario'),
    path('pdf-reportlab/', relatorio_funcionarios, name='relatorio_funcionarios'),
    path('relatorio_funcionarios_html/', Pdf.as_view(), name='relatorio_funcionarios_html'),
]

projetoOpe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from apps_gerais.funcionarios.api.views import FuncionarioViewSet
from apps_gerais.registro_hora_extra.api.views import RegistroHoraExtraViewSet
from rest_framework import routers
from apps_gerais.core import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/registro_hora_extra', RegistroHoraExtraViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += i18n_patterns (
    path('', include('apps_gerais.core.urls')),
    path('funcionarios/', include('apps_gerais.funcionarios.urls')),
    path('departamentos/', include('apps_gerais.departamentos.urls')),
    path('documentos/', include('apps_gerais.documentos.urls')),
    path('empresa/', include('apps_gerais.empresa.urls')),
    path('horas-extras/', include('apps_gerais.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('usuarios/', include('apps_gerais.usuarios.urls')),
    path('produto/', include('apps_gerais.produto.urls')),
    path('estoque/', include('apps_gerais.estoque.urls')),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps_gerais/documentos/models.py
from django.db import models
from apps_gerais.funcionarios.models import Funcionario
from django.shortcuts import reverse

# Create your models here.

class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao


    

apps_gerais/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from apps_gerais.departamentos.models import Departamento
from apps_gerais.empresa.models import Empresa
from django.urls import reverse
from django.db.models import Sum

class Funcionario(models.Model):
	nome = models.CharField(max_length=100)
	cpf = models.CharField('CPF', max_length=11, unique=True)
	idade = models.IntegerField()
	email = models.EmailField(unique=True)
	telefone = models.CharField(max_length=20, blank=True)
	user = models.OneToOneField(User, on_delete=models.PROTECT)
	departamentos = models.ManyToManyField(Departamento)
	empresa = models.ForeignKey(
		Empresa, on_delete=models.PROTECT, null=True, blank=True)
	imagem = models.ImageField()
	de_ferias = models.BooleanField(default=False)


	def get_absolute_url(self):
		return reverse('home')

	@property
	def total_horas_extra(self):
		total = self.registrohoraextra_set.filter(utilizada=False).aggregate(Sum('horas'))['horas__sum']
		return total or 0



	def __str__(self):
		return self.nome

apps_gerais/funcionarios/api/views.py
from rest_framework import viewsets
from apps_gerais.funcionarios.api.serializers import FuncionarioSerializer
from apps_gerais.funcionarios.models import Funcionario
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication



class FuncionarioViewSet(viewsets.ModelViewSet):
    queryset = Funcionario.objects.all()
    serializer_class = FuncionarioSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

apps_gerais/funcionarios/views.py
#import password as password
from django.views.generic import(ListView,
                                UpdateView,
                                DeleteView,
                                CreateView,
                                DetailView
)
from .models import Funcionario
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views import View

from django.http import HttpResponse
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas

from django.template.loader import get_template
import xhtml2pdf.pisa as pisa



class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        try:
            empresa_logada = self.request.user.funcionario.empresa
            return Funcionario.objects.filter(empresa=empresa_logada)
        except Exception as e:
            return Funcionario.objects.all()

class FuncionarioDetail(DetailView):
    model = Funcionario


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome','cpf','idade','email','telefone',
    'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome','cpf','idade','email','telefone',
    'departamentos','empresa']

    def form_valid(self, form):
        try:
            funcionario = form.save(commit=False)
            username = funcionario.email
            funcionario.empresa = self.request.user.funcionario.empresa
            funcionario.user = User.objects.create(username=username)
            funcionario.password = User.objects.create(password=password)
            funcionario.save()
            return super(FuncionarioNovo, self).form_valid(form)
        except:
            funcionario = form.save(commit=False)
            username = funcionario.email
            #Depois precisa colocar algum validador 
            # ele dá erro com unique em relação ao nome de usuário por  estár igual ao(não aceita dois emails iguais) email agora, mas só no envio
            funcionario.empresa = funcionario.empresa
            funcionario.user = User.objects.create(username=username)
            #funcionario.password = User.objects.create(password=password)
            #Ele não está importando password 
            funcionario.save()
            return super(FuncionarioNovo, self).form_valid(form)




# gerar relatório reportlab pesquisar para efetuar melhorias
def relatorio_funcionarios(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] ='attachment; filename="mypdf.pdf"'

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)

    p.drawString(200, 810, 'Relatório de funcionarios')

    try:
        funcionarios = Funcionario.objects.filter(empresa=request.user.funcionario.empresa)
        str_ = 'Nome: %s   |Hora extra: %.2f'
        p.drawString(0, 800, '_'*150)

        y = 750
        for funcionario in funcionarios:
            p.drawString(10, y, str_ %(funcionario.nome, funcionario.total_horas_extra))
            y -= 20

        p.showPage()
        p.save

        pdf =buffer.getvalue()
        buffer.close()
        response.write(pdf)

        return response

    except:
        funcionarios = Funcionario.objects.all()
        str_ = 'Nome: %s   |Hora extra: %.2f'

        p.drawString(0, 800, '_'*150)

        y = 750
        for funcionario in funcionarios:
            p.drawString(10, y, str_ %(funcionario.nome, funcionario.total_horas_extra))
            y -= 20

        p.showPage()
        p.save


        pdf =buffer.getvalue()
        buffer.close()
        response.write(pdf)

        return response

class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html =template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type='application/pdf')
            response['Content-Disposition'] ='attachment;filename=%s.pdf' % filename
            return response
        else:
            return HttpResponse("Erro Rendering PDF", status=400)


class Pdf(View):

    def get(self, request):
        params = {
            'today': 'Variavel today',
            'sales': 'Variavel sales',
            'request': request,
        }
        return Render.render('funcionarios/relatorio.html', params, 'myfile')

apps_gerais/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}

<h4 class="list-group-item list-group-item-primary">Editar cadastro de Funcionarios</h4>

<form method="POST">
    {% csrf_token %}
    <h4>Você tem certeza que quer deletar: {{ object }}</h4>

    {{ form }}
    <button type="submit" class="btn btn-danger">Confirmar</button>
</form>

{% endblock %}

apps_gerais/funcionarios/templates/funcionarios/funcionario_detail.html
{% extends 'base.html' %}


{% block main %}
<br>
<h4 class="list-group-item list-group-item-primary">Detalhes do Funcionario</h4>
<ul class="list-group">
  <li class="list-group-item list-group-item-success">
<p><strong>Nome: </strong>{{ funcionario.nome|upper }}</p>
<p><strong>CPF:</strong> {{ funcionario.cpf }}</p>
<p><strong>Idade:</strong> {{ funcionario.idade }}</p>
<p><strong>Email:</strong> {{ funcionario.email }}</p>
<p><strong>Telefone:</strong> {{ funcionario.telefone }}</p>
<p><strong>Total de horas extras:</strong>  {{ object.total_horas_extra }} </p>


  </li>
</ul>
<span class="btn btn-warning">
    <a href="{% url 'update_funcionario' funcionario.id %}">
            Alterar
</span></a>
<span class="btn btn-danger">
    <a href="{% url 'delete_funcionario' funcionario.id %}">
            Deletar
</span></a>


{% endblock %}

apps_gerais/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}


<form method="POST">
    {% csrf_token %}

    {{ form|bootstrap }}

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>
    <br>
    <a href="{% url 'create_empresa' %}">
      <button type="button" class="btn btn-primary">
        <span class="fa fa-plus"></span> Adicionar Empresa
      </button>
    </a>

    
    <a href="{% url 'create_departamento' %}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar Departamento 
        </button>
    </a>
<br>
<h5>Documentos</h5>
<ul>
{% for documento in object.documento_set.all %}
    <li>
      <a href="{{ documento.arquivo.url }}"> {{ documento.descricao }} </a><br>
    </li>
{% endfor %}
</ul>

  {% if object %}
      <a href="{% url 'create_documento'  object.id %}" class="btn btn-success">Adicionar Documento</a>
    {% endif %}

<h5>Banco de Horas</h5>
<ul>
{% for registro_hora in object.registrohoraextra_set.all %}
    <li>
      <a href="{% url 'update_horas-extras' registro_hora.id %}">{{ registro_hora.motivo }} | {{ registro_hora.horas }} </a><br>
    </li>
{% endfor %}

</ul>
<h5>Total de horas extras: {{ object.total_horas_extra }} </h5>
  {% if object %}
      <a href="{% url 'create_horas-extras' %}" class="btn btn-success">Adicionar Hora Extras</a>
  {% endif %}

{% endblock %}

apps_gerais/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
<h4 class="list-group-item list-group-item-primary">Lista de Funcionários</h4>


<ul class="list-group">
  <li class="list-group-item list-group-item-success">

    {% for funcionario in object_list %}


           {{funcionario|upper}}

      <span class="badge badge-warning">
        <a href="{% url 'detalhe_funcionario' funcionario.id %}">
            Detalhe
        </span>
        </a>
        <br>
    {% endfor %}

  </li>
</ul>

    <a href="{% url 'create_funcionario' %}" class="btn btn-info"> Novo </a>


    <a href="{% url 'relatorio_funcionarios' %}" class="btn btn-info">Relatório Funcionarios</a>
    <a href="{% url 'relatorio_funcionarios_html' %}" class="btn btn-info">Relatório Funcionarios HTML</a>



{% endblock %}