apps_gerais/produto/urls.py
from django.urls import path
from apps_gerais.produto import views as v


app_name = 'produto'


urlpatterns = [
    path('', v.ProdutoList.as_view(), name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('<int:pk>/json/', v.produto_json, name='produto_json'),
]

projetoOpe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from apps_gerais.funcionarios.api.views import FuncionarioViewSet
from apps_gerais.registro_hora_extra.api.views import RegistroHoraExtraViewSet
from rest_framework import routers
from apps_gerais.core import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/registro_hora_extra', RegistroHoraExtraViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += i18n_patterns (
    path('', include('apps_gerais.core.urls')),
    path('funcionarios/', include('apps_gerais.funcionarios.urls')),
    path('departamentos/', include('apps_gerais.departamentos.urls')),
    path('documentos/', include('apps_gerais.documentos.urls')),
    path('empresa/', include('apps_gerais.empresa.urls')),
    path('horas-extras/', include('apps_gerais.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('usuarios/', include('apps_gerais.usuarios.urls')),
    path('produto/', include('apps_gerais.produto.urls')),
    path('estoque/', include('apps_gerais.estoque.urls')),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps_gerais/produto/models.py
from django.db import models
from django.urls import reverse_lazy
from django.core import validators
from django.core.exceptions import ValidationError


def validate_even(value):
    if len(value) != 8:
        raise ValidationError(('Em %(value)s. Faltam dígitos')
        ,params={'value': value},)
    for n in value:
        try:
           n=int(n) 
        except:
            raise ValidationError(('Em %(value)s. Algum valor inserido não é um número')
            ,params={'value': value},)
                

class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM',max_length=8, validators=[validate_even], unique=True)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque mínimo', default=0)

    class Meta:
        ordering = ('produto',)
    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }

apps_gerais/produto/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

apps_gerais/produto/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, ListView
from .models import Produto
from .forms import ProdutoForm


def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    search = request.GET.get('search')
    if search:
        objects = objects.filter(produto__icontains=search)
    context = {'object_list': objects}
    return render(request, template_name, context)


class ProdutoList(ListView):
    model = Produto
    template_name = 'produto_list.html'
    paginate_by = 10


def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


def produto_add(request, pk):
    template_name = 'produto_form.html'
    return render(request, template_name)
'''
def deleta_produto(request, pk):
    produto =  Produto.objects.get(pk=pk)
    if request.method == 'POST':
        produto.delete()
        return redirect(produto_list)
'''
        
class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


def produto_json(request, pk):
    ''' Retorna o produto, id e estoque. '''
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})

apps_gerais/produto/templates/produto_detail.html
{% extends "base.html" %}

{% block main %}

  <a href="{% url 'produto:produto_list' %}">Voltar</a>

  <h1>{{ object }}
    <span class="pull-right">
      <a href="{% url 'produto:produto_edit' object.pk %}">
        <button type="button" class="btn btn-success">
          <span class="fa fa-pencil"></span> Editar
        </button>
      </a>
    </span>
  </h1>

  <div class="col-sm-6">
    <table class="table table-user-information">
      <tbody>
        <tr>
          <th class="text-right">Importado</th>
          <td>
            {% if object.importado %}
              <i class="fa fa-check-circle ok"></i>
            {% else %}
              <i class="fa fa-minus-circle no"></i>
            {% endif %}
          </td>
          </tr>
          <tr>
            <th class="text-right">NCM</th>
            <td>{{ object.ncm }}</td>
          </tr>
          <tr>
            <th class="text-right">Preço</th>
            <td>R$ {{ object.preco }}</td>
          </tr>
          <tr>
            <th class="text-right">Estoque</th>
            <td>{{ object.estoque }}</td>
          </tr>
          <tr>
            <th class="text-right">Estoque mínimo</th>
            <td>{{ object.estoque_minimo }}</td>
          </tr>
        </tbody>
    </table>
  </div>

{% endblock main%}

apps_gerais/produto/templates/produto_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block main %}

<form method="POST" novalidate>
  {% csrf_token %}
  {% for field in form.visible_fields %}
    <div class="form-group{% if field.errors %} has-error {% endif%}">
      <label for="{{ field.id_for_label }}">
        {% if field.field.required %}
          <span class="required">{{ field.label }} </span>
        {% else %}
          {{ field.label }}
        {% endif %}
      </label>
      {% render_field field class="form-control" %}
      {% for error in field.errors %}
        <span class="text-muted">{{ error }}</span>
      {% endfor %}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock main %}

{% block js %}
  <script src="{% static 'js/produto.js' %}"></script>

{% endblock js %}

apps_gerais/produto/templates/produto_list.html
{% extends "base.html" %}

{% block main %}


<div class="page-header">
  <h2>Lista de Produtos
    <span class="pull-right">
      <a href="{% url 'produto:produto_add' %}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
    </span>
  </h2>
   <br>

  {% if object_list %}
    

    <br>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="text-center">Importado</th>
          <th class="text-center">NCM</th>
          <th class="text-center">Produto</th>
          <th class="text-center">Preço</th>
          <th class="text-center">Estoque</th>
          <th class="text-center">Estoque mínimo</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>
              {% if object.importado %}
                <i class="fa fa-check-circle ok"></i>
              {% else %}
                <i class="fa fa-minus-circle no"></i>
              {% endif %}
            </td>
            <td>{{ object.ncm }}</td>
            <td>
              <a href="{{ object.get_absolute_url }}">{{ object.produto }}</a>
            </td>
            <td>R$ <span class="pull-right">{{ object.preco }}</span></td>
            <td class="text-center">{{ object.estoque }}</td>
            <td class="text-center">{{ object.estoque_minimo }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% include "includes/pagination.html" %}

{% endblock main %}