apps_gerais/estoque/urls.py
from django.urls import include, path
from apps_gerais.estoque import views as v


app_name = 'estoque'


entrada_patterns = [
    path('', v.EstoqueEntradaList.as_view(), name='estoque_entrada_list'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
]

saida_patterns = [
    path('', v.EstoqueSaidaList.as_view(), name='estoque_saida_list'),
    path('add/', v.estoque_saida_add, name='estoque_saida_add'),
]

urlpatterns = [
    path('<int:pk>/', v.EstoqueDetail.as_view(), name='estoque_detail'),
    path('entrada/', include(entrada_patterns)),
    path('saida/', include(saida_patterns)),
]

apps_gerais/produto/urls.py
from django.urls import path
from apps_gerais.produto import views as v


app_name = 'produto'


urlpatterns = [
    path('', v.ProdutoList.as_view(), name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('<int:pk>/json/', v.produto_json, name='produto_json'),
]

projetoOpe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from apps_gerais.funcionarios.api.views import FuncionarioViewSet
from apps_gerais.registro_hora_extra.api.views import RegistroHoraExtraViewSet
from rest_framework import routers
from apps_gerais.core import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/registro_hora_extra', RegistroHoraExtraViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += i18n_patterns (
    path('', include('apps_gerais.core.urls')),
    path('funcionarios/', include('apps_gerais.funcionarios.urls')),
    path('departamentos/', include('apps_gerais.departamentos.urls')),
    path('documentos/', include('apps_gerais.documentos.urls')),
    path('empresa/', include('apps_gerais.empresa.urls')),
    path('horas-extras/', include('apps_gerais.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('usuarios/', include('apps_gerais.usuarios.urls')),
    path('produto/', include('apps_gerais.produto.urls')),
    path('estoque/', include('apps_gerais.estoque.urls')),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps_gerais/core/models.py
from django.db import models

class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

apps_gerais/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from apps_gerais.funcionarios.models import Funcionario
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from apps_gerais.core.serializers import UserSerializer, GroupSerializer
from django.http import HttpResponse
from .tasks import send_relatorio
from django.db.models import Sum
from .tasks import send_relatorio
from apps_gerais.registro_hora_extra.models import RegistroHoraExtra


@login_required
def home(request):
    data = {}
    data['usuario'] = request.user
    try:
        funcionario = request.user.funcionario
        data['total_funcionarios'] = funcionario.empresa.total_funcionarios
        data['total_funcionarios_ferias'] = funcionario.empresa.total_funcionarios_ferias
        data['total_funcionarios_doc_ok'] = funcionario.empresa.total_funcionarios_doc_ok
        data['total_funcionarios_doc_pendente'] = funcionario.empresa.total_funcionarios_doc_pendente
        data['total_funcionarios_rg'] = 10
        data['total_funcionarios_doc_pendente'] = funcionario.empresa.total_funcionarios_doc_pendente
        data['total_hora_extra_utilizadas'] = RegistroHoraExtra.objects.filter(
            funcionario__empresa=funcionario.empresa, utilizada=True).aggregate(Sum('horas'))['horas__sum']
        data['total_hora_extra_pendente'] = RegistroHoraExtra.objects.filter(
            funcionario__empresa=funcionario.empresa, utilizada=False).aggregate(Sum('horas'))['horas__sum']
        return render(request, 'core/index.html', data)
    except Exception as e:
        return render(request, 'core/index.html', data)
       #return HttpResponse('Você não tem funcionários, não sei entrou no except, deve ser isso')


def celery(request):
		send_relatorio.delay()
		return HttpResponse('Tarefa incluida na fila para execução')


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

apps_gerais/core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse in " data-target="#navbars" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto h5 centro">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:index' %}">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'produto:produto_list' %}">Produtos</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estoque</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">

                    <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Entrada</a>
                    <a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}">Saída</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caixa:caixa_list' %}">Funcionários</a>
                </li>
            </li>
        
            <li class="nav-item">
                <a class="nav-link" href="{% url 'produto:produto_list' %}">TESTE</a>
            </li>

        </ul>
        {% if user.is_authenticated %}
          <ul class="navbar-nav h5 ">
            <li class="nav-item text-nowrap">
              <a href="{% url 'logout' %}" class="nav-link">Sair</a>
            </li>
          </ul>
        {% else %}
        <ul class="navbar-nav h5 ">
            <li class="nav-item text-nowrap">
                <a href="{% url 'login' %}" class="nav-link">Entrar</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

apps_gerais/core/templates/includes/pagination.html
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
      {% endif %}

      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}
          <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
        {% else %}
          {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %}
            <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
            <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="">...</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>